# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='document',
            field=models.FileField(default='DEFAULT_CONVENTION_DOCUMENT', upload_to=documents.models.upload_destination),
        ),
    ]
