# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-01 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consult_panel', '0002_remove_entreprise_siret'),
        ('documents', '0002_convention_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='cours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consult_panel.Cours'),
            preserve_default=False,
        ),
    ]
