# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-08 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='siret',
        ),
    ]
