# Generated by Django 2.0.5 on 2018-05-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_panel', '0002_remove_entreprise_siret'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='representant_nom',
            field=models.CharField(default='Dupont', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='representant_prenom',
            field=models.CharField(default='Jean', max_length=200),
            preserve_default=False,
        ),
    ]
