# Generated by Django 2.0.5 on 2018-05-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_panel', '0004_actionformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionformation',
            name='code',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
