# Generated by Django 2.0.5 on 2018-05-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_panel', '0005_actionformation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionformation',
            name='code',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
