# Generated by Django 2.0.5 on 2018-05-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consult_panel', '0006_auto_20180512_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='action_formation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='consult_panel.ActionFormation'),
            preserve_default=False,
        ),
    ]
