# Generated by Django 2.0.5 on 2018-05-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult_panel', '0010_profile_tva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='prix_ttc',
        ),
    ]
