# Generated by Django 2.0.5 on 2018-05-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult_panel', '0013_auto_20180513_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localisation',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='localisation',
        ),
        migrations.DeleteModel(
            name='Localisation',
        ),
    ]
