# Generated by Django 2.0.5 on 2018-05-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_panel', '0014_auto_20180513_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionformation',
            name='objectif',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionformation',
            name='public',
            field=models.CharField(default='public', max_length=255),
            preserve_default=False,
        ),
    ]
