# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import document_generator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consult_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110)),
                ('document', models.FileField(max_length=500, upload_to=document_generator.models.upload_destination)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult_panel.Profile')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_generator.DocumentType')),
            ],
        ),
    ]
