# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='document_generator.DocumentType'),
            preserve_default=False,
        ),
    ]
