# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0002_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
    ]
