# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 15:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0003_auto_20160512_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='document',
            field=models.FileField(default=datetime.datetime(2016, 6, 12, 15, 3, 33, 810991, tzinfo=utc), upload_to='admin_documents/'),
            preserve_default=False,
        ),
    ]
