# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import document_generator.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0004_template_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='document',
            field=models.FileField(upload_to=document_generator.models.upload_destination),
        ),
    ]
