# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0006_auto_20160613_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='profile',
        ),
    ]
