# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consult_panel', '0002_auto_20160512_1842'),
        ('document_generator', '0007_remove_template_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='consult_panel.Profile'),
            preserve_default=False,
        ),
    ]
